### ISSUE TITLE
Multilanguage messages

### ISSUE THREAD

**Issue by Takeno** [Takeno/magic-judges-event-bot#2]
Allow different translations for messages published on discord

**Comment by pnicolli** [comment]
@Takeno I can give this a shot. My plan would be to add an entry in the configuration file, a separate `i18n` folder with a js module per language exporting an object with a key/value mapping of translated strings.

What do you think?

**Comment by Takeno** [comment]
Sounds great! As long as we have just one text localized, I think we don't need an external lib.

The only one thing that makes me not sure is how specify locale. I'm looking for a solution for #1.

**Comment by Takeno** [comment]
Implemented by the great work of @pnicolli with #5.

Thank you Piero!
